pipeline {
    agent any
    stages {
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Stage1"){
            steps{
                "echo This is stage1"
            }
        }
        stage("Stage2"){
            steps{
                "echo This is stage2"
            }
        }
        stage("Stage3"){
            steps{
                "echo This is stage3"
            }
        }
        stage("Stage4"){
            steps{
                "echo This is stage4"
            }
        }
        stage("Stage5"){
            steps{
                "echo This is stage5"
            }
        }
    }
}